### ISSUE TITLE
Automate Snapshot banner display

### ISSUE THREAD

**Issue by silochad** [BeanstalkFarms/Beanstalk-Landing#227]
![image](https://user-images.githubusercontent.com/99763686/210807137-85ba960b-587b-4129-9976-28effe9c5557.png)

Right now, we manually update snapshot IDs to show the following items. Let's use Snapshot's API to pull the latest proposals. The Beanstalk UI, see `state/beanstalk/governance/updater.ts`.

**Comment by hellofromguy** [comment]
these should also route to the app.bean.money governance page, not snapshot @imcoolbean
